MVC_SHOP/Controllers/FeedBacksController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using MVC_SHOP.Common;
using MVC_SHOP.Models;
using PagedList;

namespace MVC_SHOP.Controllers
{
    public class FeedBacksController : Controller
    {
        private LearnContext db = new LearnContext();
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "name" : "";
            ViewBag.DateSortParm = sortOrder == "Created" ? "CreatedDate_desc" : "CreatedDate";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var feedback = from s in db.FeedBacks
                        select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                feedback = feedback.Where(s => s.name.Contains(searchString)
                                         || s.Email.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name":
                    feedback = feedback.OrderByDescending(s => s.name);
                    break;
                case "CreatedDate_desc":
                    feedback = feedback.OrderBy(s => s.Creared);
                    break;
                case "CreatedDate":
                    feedback = feedback.OrderByDescending(s => s.Creared);
                    break;
                default:  // Name ascending 
                    feedback = feedback.OrderBy(s => s.name);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(feedback.ToPagedList(pageNumber, pageSize));
        }
        public void ExportData()
        {
            
           var lstFeedBack = db.FeedBacks.ToList();

            WebGrid webGrid = new WebGrid(lstFeedBack, canPage: true, rowsPerPage: 10);
            string gridData = webGrid.GetHtml(
                columns: webGrid.Columns(
                webGrid.Column(columnName: "name", header: "Name"),
                webGrid.Column(columnName: "Email", header: "Email"),
                webGrid.Column(columnName: "Content", header: "Content"),
                webGrid.Column(columnName: "PhoneNumber", header: "PhoneNumber"),
                webGrid.Column(columnName: "Creared", header: "Creared")
            )).ToString();

            Response.ClearContent();
            Response.AddHeader("content-disposition", "attachment; filename=FeedBack-Details.xls");
            Response.ContentType = "applicatiom/excel";
            Response.Write(gridData);
            Response.End();
        }
        // GET: FeedBacks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Default");
            }
            FeedBacks feedBacks = db.FeedBacks.Find(id);
            if (feedBacks == null)
            {
                return HttpNotFound();
            }
            return View(feedBacks);
        }

        // GET: FeedBacks/Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FeedBacks feedBacks)
        {
            feedBacks.ModifieddBy = Notice.SystemAddmin;
            feedBacks.Creared = DateTime.Now;
            feedBacks.Modified = DateTime.Now;
            feedBacks.CreatedBy = Notice.SystemAddmin;
            if (ModelState.IsValid)
            {
                db.FeedBacks.Add(feedBacks);
                db.SaveChanges();
                return RedirectToAction(Notice.Index);
            }

            return View(feedBacks);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNew(FeedBacks feedBacks)
        {
            feedBacks.ModifieddBy = Notice.SystemAddmin;
            feedBacks.Creared = DateTime.Now;
            feedBacks.Modified = DateTime.Now;
            feedBacks.CreatedBy = Notice.SystemAddmin;
            string content = "You have notification from Bright Day center \n" +
                             "Member " + feedBacks.name + " has mail is: \n" + feedBacks.Email
                             +" Response content: \n" + feedBacks.Content + "\n at " + feedBacks.Creared;
            if (ModelState.IsValid)
            {
                db.FeedBacks.Add(feedBacks);
                db.SaveChanges();
                var sendMail = new SendMail.EmailService();
                sendMail.Send(Notice.MailXuan, Notice.Subject1, content);
                return RedirectToAction(Notice.Index, Notice.Home);
            }
            return  RedirectToAction(Notice.Index, Notice.Home);
        }

        // GET: FeedBacks/Edit/5
        public ActionResult Edit(int? id)
        { 
                if (id == null)
                {
                    return RedirectToAction("Error", "Default");
                }
                FeedBacks feedBacks = db.FeedBacks.Find(id);
                if (feedBacks == null)
                {
                    return HttpNotFound();
                }
                return View(feedBacks);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( FeedBacks feedBacks)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feedBacks).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction(Notice.Index);
            }
            return View(feedBacks);
        }

        // GET: FeedBacks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Default");
            }
            FeedBacks feedBacks = db.FeedBacks.Find(id);
            if (feedBacks == null)
            {
                return HttpNotFound();
            }
            return View(feedBacks);
        }

        // POST: FeedBacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FeedBacks feedBacks = db.FeedBacks.Find(id);
            if (feedBacks != null) db.FeedBacks.Remove(feedBacks);
            db.SaveChanges();
            return RedirectToAction(Notice.Index);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_SHOP/Controllers/HomeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MVC_SHOP.Models;

namespace MVC_SHOP.Controllers
{
    public class HomeController : Controller
    {
        private LearnContext db = new LearnContext();
        public ActionResult Index()
        {
            ViewBag.Cat1 = db.News.Where(c => c.Catrgories.Title == "Education").Take(4);
            ViewBag.Cat2 = db.News.Where(c => c.Catrgories.Title == "Public").Take(4);
            ViewBag.Cat3 = db.News.Where(c => c.Catrgories.Title == "Promotion").Take(4);
            ViewBag.Cat4 = db.News.Where(c => c.Catrgories.Title == "Society").Take(4);
            ViewBag.isHome = true;
            return View();
        }
    }
}

MVC_SHOP/Views/Home/Index.cshtml
@model MVC_SHOP.Models.FeedBacks
@{
    ViewBag.Title = "Home Page";
}
<body>

@{Html.RenderPartial("~/Views/Shared/PartialsView/_SlidePartialView.cshtml"); }
@{Html.RenderPartial("~/Views/Shared/PartialsView/_MenuCenterPartialView.cshtml"); }

<section class="section-col-blogs sectionHome">
    <div class="container">
        <div class="row">

        </div>
        <div class="row Title">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="col-title">
                    <h3>
                        <a href="#" title="Thông Tin Khóa Học"><b>Thông Tin Khóa Học</b></a>
                    </h3>
                </div>
                <div class="content-col hover14 column">
                    <div class="img1 blog-item-thumbnail" onclick="location.href = '#';">
                        <a href="#"><figure><img src="~/images/Image Briday/Image3.jpg"/></figure></a>
                    </div>
                    @foreach (var item in ViewBag.Cat1)
                    {
                        <hr/>
                        <h4 class="blog-item-name"><a href="/news/Details/@item.Id">@item.Title</a></h4>
                    }
                    <hr/>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="col-title">
                    <h3>
                        <a href="#" title="Nổi Bật"><b>Nổi Bật</b></a>
                    </h3>
                </div>
                <div class="content-col hover14 column">
                    <div class="img1 blog-item-thumbnail" onclick="location.href = '#';">
                        <a href="#"><figure><img src="~/images/Image Briday/Noibat.jpg"/></figure></a>
                    </div>
                    @foreach (var item in ViewBag.Cat2)
                    {
                        <hr/>
                        <h4 class="blog-item-name"><a href="/news/Details/@item.Id">@item.Title</a></h4>
                    }
                    <hr/>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="col-title">
                    <h3>
                        <a href="#" title="Tư Vấn"><b>Tư Vấn</b></a>
                    </h3>
                </div>
                <div class="content-col hover14 column">
                    <div class="img1 blog-item-thumbnail" onclick="location.href = '#';">
                        <a href="#"><figure><img src="~/images/Image Briday/Image4.jpg"/></figure></a>
                    </div>
                    @foreach (var item in ViewBag.Cat3)
                    {
                        <hr/>
                        <h4 class="blog-item-name"><a href="/news/Details/@item.Id">@item.Title</a></h4>
                    }
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="col-title">
                    <h3>
                        <a href="#" title="Video & Hình ảnh"><b>Video & Hình ảnh</b></a>
                    </h3>
                </div>
                <div class="content-col hover14 column">
                    <div class="img1 blog-item-thumbnail" onclick="location.href = '#';">
                        <a href="#"><figure><img src="~/images/Image Briday/Image5.jpg"/></figure></a>
                    </div>@foreach (var item in ViewBag.Cat4)
                          {
                              <hr/>
                              <h4 class="blog-item-name"><a href="/news/Details/@item.Id">@item.Title</a></h4>

                          }
                </div>
            </div>
        </div>
    </div>
</section>
@using (Html.BeginForm("CreateNew", "FeedBacks", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <section class="bg_section">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="form_ct_index">
                        <div>
                            <h2 class="title-box-fu"> Gửi câu hỏi hỗ trợ</h2>
                        </div>
                        <span>                        Bạn muốn nhận được hỗ trợ tư vấn nhanh nhất. Hãy gửi ngay câu hỏi về email của chúng tôi ngay.</span>
                        <div class="form-booking clearfix" style="padding-top: 10px;">
                            <fieldset class="form-group">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control",@id = "Name", placeholder = "Tên của bạn" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </fieldset>
                            <fieldset class="form-group">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email", @id = "Mail" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </fieldset>
                            <fieldset class="form-group">
                                @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control"} })
                                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                            </fieldset>
                            <div class="btn btn-50-blue">
                                <input type="submit" value="Gửi ngay" style="background-color: #13a6ef" class="btn"><i class="fa fa-angle-right" aria-hidden="true"></i>
                            </div>
                        </div>
                        <br />
                        <a class="btn btn-50-orange" href="tel:0968063893">Gọi ngay: 0968063893</a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="row col-rht">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="col-title">
                                <h2><a href="khoa-hoc-online" title="Khoá học online">Khoá học online</a></h2>
                            </div>
                        </div>
                        <div class="blog_large">

                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <article class="blog-item">
                                    <div class="img1 blog-item-thumbnail" onclick="location.href='/13-khoa-hoc-online-tot-nhat-nam-2017-chi-voi-hoc-phi-10-usd';">
                                        <a href="/13-khoa-hoc-online-tot-nhat-nam-2017-chi-voi-hoc-phi-10-usd">

                                            <picture>
                                                <source srcset="//bizweb.dktcdn.net/thumb/large/100/216/031/articles/phan-mem-ke-toan-mien-phi-cho-doanh-nghiep-nho-5.jpg?v=1495515113787" media="(max-width: 480px)">
                                                <img src="//bizweb.dktcdn.net/thumb/large/100/216/031/articles/phan-mem-ke-toan-mien-phi-cho-doanh-nghiep-nho-5.jpg?v=1495515113787" alt="13 khóa học online tốt nhất năm 2017 chỉ với học phí 10 USD">
                                            </picture>

                                        </a>
                                    </div>
                                    <div class="post-time">
                                        23 THÁNG NĂM 2017
                                    </div>
                                    <h3 class="blog-item-name1"><a class="text3line" href="/13-khoa-hoc-online-tot-nhat-nam-2017-chi-voi-hoc-phi-10-usd" title="13 khóa học online tốt nhất năm 2017 chỉ với học phí 10 USD">13 khóa học online tốt nhất năm 2017 chỉ với học phí 10 USD</a></h3>
                                </article>
                            </div>

                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <article class="blog-item">
                                    <div class="img1 blog-item-thumbnail" onclick="location.href='/10-khoa-hoc-truc-tuyen-mien-phi-tu-cac-truong-danh-tieng-tren-toan-cau';">
                                        <a href="/10-khoa-hoc-truc-tuyen-mien-phi-tu-cac-truong-danh-tieng-tren-toan-cau">

                                            <picture>
                                                <source srcset="//bizweb.dktcdn.net/thumb/large/100/216/031/articles/apply-nhan-ngay-hoc-bong.jpg?v=1495514778687" media="(max-width: 480px)">
                                                <img src="//bizweb.dktcdn.net/thumb/large/100/216/031/articles/apply-nhan-ngay-hoc-bong.jpg?v=1495514778687" alt="10 khóa học trực tuyến miễn phí từ các trường danh tiếng trên toàn cầu">
                                            </picture>

                                        </a>
                                    </div>
                                    <div class="post-time">
                                        23 THÁNG NĂM 2017
                                    </div>
                                    <h3 class="blog-item-name1"><a class="text3line" href="/10-khoa-hoc-truc-tuyen-mien-phi-tu-cac-truong-danh-tieng-tren-toan-cau" title="10 khóa học trực tuyến miễn phí từ các trường danh tiếng trên toàn cầu">10 khóa học trực tuyến miễn phí từ các trường danh tiếng trên toàn cầu</a></h3>
                                </article>
                            </div>
                        </div>
                        <div class="list_blog_title col-lg-12 col-md-12 col-sm-12 col-xs-12">

                            <div class="item_name_blog_list"><h3 class="blog-item-name content:1"><a class="text2line" href="/du-hoc-online-dai-hoc-queen-s-tai-sao-khong-co-hoi-cho-cac-ban-tre" title="Du học Online đại học Queen’s tại sao không? Cơ hội cho các bạn trẻ biến ước mơ du học hành hiện thực">Du học Online đại học Queen’s tại sao không? Cơ hội cho các bạn trẻ biến ước mơ du học hành hiện thực</a></h3></div>

                            <div class="item_name_blog_list"><h3 class="blog-item-name"><a class="text2line" href="/cac-truong-dai-hoc-uc-mo-cac-khoa-hoc-truc-tuyen-mien-phi" title="Các trường đại học Úc mở các khoá học trực tuyến miễn phí">Các trường đại học Úc mở các khoá học trực tuyến miễn phí</a></h3></div>

                            <div class="item_name_blog_list"><h3 class="blog-item-name"><a class="text2line" href="/dang-ki-tham-du-ngay-khoa-hoc-usmle-online-cua-kaplan-medical-2017" title="Đăng kí tham dự ngay khóa học USMLE Online của Kaplan Medical 2017">Đăng kí tham dự ngay khóa học USMLE Online của Kaplan Medical 2017</a></h3></div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}


</body>